### ISSUE TITLE
arrayfire print

### ISSUE THREAD

**Issue by sconde** [arrayfire/arrayfire_examples#2]
I am trying to play around with arrayfire before making a suggestion to my advisor for us to use it in our code. While trying to compile the exam code, I get the following errors:

		cc helloworld.cpp -DOS_LNX -m64 -Wall  -lstdc++ -I/usr/local/include -pthread -O2 -DNDEBUG -DAFCL -Wl,--no-as-needed -L/usr/local/lib -lpthread -lm -Wl,-rpath,/usr/local/lib,-rpath,/usr/local/lib -lafcl -lstdc++ -o helloworld_ocl
		helloworld.cpp: In function ‘int main(int, char**)’:
		helloworld.cpp:17:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(A);
						^
		helloworld.cpp:21:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(B);
						^
		helloworld.cpp:25:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(C);
						^
		helloworld.cpp:29:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(c);
						^
		helloworld.cpp:35:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(B);
						^
		helloworld.cpp:39:26: error: reference to ‘afHost’ is ambiguous
				 array D(2, 3, d, afHost);
								  ^
		In file included from /usr/local/include/af/array.h:11:0,
						 from /usr/local/include/af/compatible.h:11,
						 from /usr/local/include/arrayfire.h:11,
						 from helloworld.cpp:2:
		/usr/local/include/af/defines.h:89:2: note: candidates are: af_source afHost
		  afHost,
		  ^
		In file included from /usr/local/include/af/compatible.h:11:0,
						 from /usr/local/include/arrayfire.h:11,
						 from helloworld.cpp:2:
		/usr/local/include/af/array.h:26:9: note:                 af::af_source_t afHost
				 afHost    ///< Host-memory pointer
				 ^
		helloworld.cpp:40:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(D);
						^
		helloworld.cpp:44:16: error: cannot convert ‘af::array’ to ‘const char*’ for argument ‘1’ to ‘void af::print(const char*, const af::array&)’
				 print(D);
						^
		helloworld.cpp:50:9: error: ‘free’ is not a member of ‘af::array’
				 array::free(d_);
				 ^
		make: *** [helloworld_ocl] Error 1

any help and hints will be much appreciated. I'm using Ubuntu 14.04.

**Comment by shehzan10** [comment]
From your compile command, It looks like you are using ArrayFire 2.1 and not the open source version. Are you sure you built the Open Source version or did you use the installers (which or only for ArrayFire 2.1).

This examples repository is meant for ArrayFire 2.1. Not all features used in these examples have been implemented by the open source version (graphics etc).

If you build the ArrayFire Open Source version from scratch, it should build the examples as well. This will be in arrayfire/build/examples.
